### ISSUE TITLE
Floating graph number doesnt reflect y-axis value

### ISSUE THREAD

**Issue by abdrysdale** [GabrielTavernini/Covid19Stats#10]
![Screenshot_20200926-081531.png](https://user-images.githubusercontent.com/13297963/94335153-8d2ce980-ffd1-11ea-883a-603c994469f4.png)

Shown in image above.

The floating graph number (the number that comes up when you touch the graph) seems to just incrementally increase from 0 to a number in the 200s. This number varies depending on the country selected but as far as I can doesn't represent the value on the y-axis.

Really enjoying the app. Keep it up!

**Comment by GabrielTavernini** [comment]
Thank you for letting me know, apparently it was displaying the value of the x-axis instead of the y-axis'. 
With the b4ed17198843f296d064c9688d60470cbf0fb328 commit it should now be fixed, I've also added separators to the tooltip text to make it easier to read.
I'll make a new release to roll out the fix as soon as possible.

**Comment by abdrysdale** [comment]
No worries at all, thank you for creating the app! Thanks for the fix too
