### ISSUE TITLE
Charts day range is broken in 2021

### ISSUE THREAD

**Issue by tux4us** [GabrielTavernini/Covid19Stats#22]
It's not possible to change the day range. The calendar is not usable and frozen. No reaction when touch the items and numbers. Other things are working fine, e.g. change the country.

**Comment by GabrielTavernini** [comment]
Thanks for letting me know. I've fixed the bug regarding the date range selector.
Despite that fix, due to how worldometers (the data source) is handling the overlapping dates, there are still some problems with the chart visualization. I'll wait to see what they do with the website before updating the code and releasing a new version.
