### ISSUE TITLE
'Total Tests' and 'Tests per Mln' showing the wrong values

### ISSUE THREAD

**Issue by nik-futrli** [GabrielTavernini/Covid19Stats#5]
**Background info:**
- Android version: 6.0.1
- Phone model: OnePlus Two
- Application version: 1.3.0
- Application source: F-Droid

**To replicate:** 
- Fire up the Covid19Stats app on your phone
- Switch to a country which publishes its tests-related data (e.g. UK)
- Check the numbers displayed in the 'Total Tests' and 'Tests per Mln' once the data have finished loading
- Compare those values with the ones for the same country on the worldometers.info website 

**Actual result:**
- The 'Total Tests' field is displaying data from the 'Deaths/1M pop' column 
- The 'Tests per Mln' field is displaying data from the 'Total Tests' column 

**Expected result:**
- The 'Total Tests' field should be displaying data from the 'Total Tests' column 
- The 'Tests per Mln' field should be displaying data from the 'Tests/1M pop' column

**Comment by GabrielTavernini** [comment]
Hi, thank you for the feedback. 
Unfortunately, the version available on F-Droid isn't the [latest one](https://github.com/GabrielTavernini/Covid19Stats/releases/latest).

The issues that you are mentioning have been fixed in the [latest version](https://github.com/GabrielTavernini/Covid19Stats/releases/latest), which is v1.6 and it is available here on GitHub under the [releases tab](https://github.com/GabrielTavernini/Covid19Stats/releases).
Hopefully the new version will soon be available on F-Droid.

**Comment by nik-futrli** [comment]
Excellent news! Thank you very much for the quick reply. I will wait for the latest version to show up on F-Droid. 😃
